name: Windows AnyDesk Setup with Chocolatey

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Install Chocolatey (if missing)
        shell: cmd
        run: |
          where choco || (
            @powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command ^
              "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
          )

      - name: Install AnyDesk
        shell: cmd
        run: choco install anydesk -y

      - name: Set AnyDesk unattended access password
        shell: powershell
        run: |
          $RegPath = 'HKLM:\SOFTWARE\AnyDesk'
          if (-not (Test-Path $RegPath)) {
            New-Item -Path $RegPath -Force | Out-Null
          }
          $Password = 'DANIEL64MACOSVM'
          $PasswordBytes = [System.Text.Encoding]::UTF8.GetBytes($Password)
          Set-ItemProperty -Path $RegPath -Name 'Password' -Value $PasswordBytes -Type Binary

      - name: Launch AnyDesk
        shell: cmd
        run: |
          if exist "C:\Program Files (x86)\AnyDesk\AnyDesk.exe" (
            start "" "C:\Program Files (x86)\AnyDesk\AnyDesk.exe"
          ) else if exist "C:\Program Files\AnyDesk\AnyDesk.exe" (
            start "" "C:\Program Files\AnyDesk\AnyDesk.exe"
          ) else (
            echo AnyDesk executable not found.
            exit /b 1
          )

      - name: Keep runner alive
        shell: cmd
        run: |
          :loop
          echo Still running...
          timeout /t 60 /nobreak > nul
          goto loop
