name: Windows AnyDesk Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-2025  # Must be a self-hosted Windows runner for GUI and AnyDesk to work

    steps:
      - name: Install Chocolatey (if missing)
        run: |
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }

      - name: Install AnyDesk via Chocolatey
        run: choco install anydesk -y

      - name: Set AnyDesk password
        run: |
          $RegPath = "HKLM:\SOFTWARE\AnyDesk"
          if (-not (Test-Path $RegPath)) {
            New-Item -Path $RegPath -Force | Out-Null
          }
          Set-ItemProperty -Path $RegPath -Name "Password" -Value ([System.Text.Encoding]::UTF8.GetBytes("DANIEL64MACOSVM") | ForEach-Object { $_.ToString("X2") }) -Type Binary

      - name: Launch AnyDesk
        run: |
          Start-Process "C:\Program Files (x86)\AnyDesk\AnyDesk.exe"
          Start-Sleep -Seconds 5

      - name: Show AnyDesk ID
        run: |
          Get-Content "$env:APPDATA\AnyDesk\system.conf" | Select-String 'ad.anynet.id' | ForEach-Object { $_.ToString() }

      - name: Keep runner alive
        run: |
          Write-Host "Setup complete. Keeping the runner alive..."
          while ($true) {
            Write-Host "Still running..."
            Start-Sleep -Seconds 60
          }
