name: AnyDesk Windows Setup with Password

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Install Chocolatey (if missing)
        shell: cmd
        run: |
          where choco || (
            powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command ^
              "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
          )

      - name: Install AnyDesk Portable
        shell: cmd
        run: choco install anydesk.portable -y

      - name: Launch AnyDesk, get ID, and set password
        shell: powershell
        run: |
          $exe = "C:\ProgramData\chocolatey\lib\anydesk.portable\tools\AnyDesk.exe"
          
          # Start AnyDesk
          Start-Process -FilePath $exe -ArgumentList '--start'
          
          # Wait and retry to get a valid ID
          $id = ""
          for ($i=0; $i -lt 10; $i++) {
              Start-Sleep -Seconds 5
              $id = & $exe --get-id
              if (![string]::IsNullOrEmpty($id) -and $id -ne "0") { break }
              Write-Host "Waiting for AnyDesk ID..."
          }
          if ([string]::IsNullOrEmpty($id) -or $id -eq "0") {
              Write-Host "Failed to get valid AnyDesk ID."
              exit 1
          }
          
          # Attempt to set password (may or may not work)
          $password = "danielrdp"
          $passwordSecureString = ConvertTo-SecureString $password -AsPlainText -Force
          # AnyDesk does not officially support this, but try:
          $process = Start-Process -FilePath $exe -ArgumentList '--set-password _full_access' -PassThru -NoNewWindow -RedirectStandardInput "pipe"
          $process.StandardInput.WriteLine($password)
          $process.StandardInput.Close()
          $process.WaitForExit()
          
          # Show info
          Write-Host ".........................................................."
          Write-Host ". Anydesk Workflow file- https://bit.ly/anydeskworkflow .."
          Write-Host ".........................................................."
          Write-Host "......#####...######...####....####...##.......####......."
          Write-Host "......##..##....##....##......##..##..##......##..##......"
          Write-Host "......##..##....##.....####...######..##......######......"
          Write-Host "......##..##....##........##..##..##..##......##..##......"
          Write-Host "......#####...######...####...##..##..######..##..##......"
          Write-Host ".........................................................."
          Write-Host "..Youtube Video Tutorial - https://youtu.be/xHr0cPjSRFg .."
          Write-Host ".........................................................."
          Write-Host "AnyDesk ID is: $id"
          Write-Host "AnyDesk Password: $password"
          Write-Host "You can login now!"

      - name: Keep runner alive silently
        shell: cmd
        run: |
          @echo off
          :loop
          ping 127.0.0.1 -n 60 >nul
          goto loop
