name: Windows AnyDesk Portable Setup (cmd)

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Download AnyDesk Portable
        run: curl.exe -L -o "%USERPROFILE%\AnyDeskPortable.exe" https://download.anydesk.com/AnyDesk.exe
        shell: cmd

      - name: Configure AnyDesk Portable Password (PowerShell helper)
        run: powershell -Command ^
          "$adConfigPath = \"$env:APPDATA\AnyDesk\"; ^
          if (-not (Test-Path $adConfigPath)) { New-Item -ItemType Directory -Path $adConfigPath | Out-Null }; ^
          $passwordBytes = [System.Text.Encoding]::UTF8.GetBytes('DANIEL64MACOSVM'); ^
          $passwordHex = $passwordBytes | ForEach-Object { $_.ToString('X2') } -join ''; ^
          $iniContent = @\"ad.password=0x$passwordHex`nad.unattended_access=true`nad.ui_access=true\"@; ^
          Set-Content -Path \"$adConfigPath\ad.ini\" -Value $iniContent"
        shell: cmd

      - name: Launch AnyDesk Portable
        run: start "" "%USERPROFILE%\AnyDeskPortable.exe"
        shell: cmd

      - name: Keep runner alive
        run: |
          :loop
          echo Still running...
          timeout /t 60 /nobreak > nul
          goto loop
        shell: cmd
