name: Windows AnyDesk Portable Setup with curl

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest  # Use self-hosted Windows runner with GUI

    steps:
      - name: Download AnyDesk Portable using curl
        run: curl.exe -L -o "%USERPROFILE%\AnyDeskPortable.exe" https://download.anydesk.com/AnyDesk.exe
        shell: cmd

      - name: Configure AnyDesk Portable Password
        run: |
          $adConfigPath = "$env:APPDATA\AnyDesk"
          if (-not (Test-Path $adConfigPath)) {
            New-Item -ItemType Directory -Path $adConfigPath | Out-Null
          }
          $passwordBytes = [System.Text.Encoding]::UTF8.GetBytes("DANIEL64MACOSVM")
          $passwordHex = $passwordBytes | ForEach-Object { $_.ToString("X2") } -join ''
          $iniContent = @"
ad.password=0x$passwordHex
ad.unattended_access=true
ad.ui_access=true
"@
          Set-Content -Path "$adConfigPath\ad.ini" -Value $iniContent
        shell: powershell

      - name: Launch AnyDesk Portable
        run: |
          Start-Process "$env:USERPROFILE\AnyDeskPortable.exe"
          Start-Sleep -Seconds 5
        shell: powershell

      - name: Show AnyDesk ID
        run: |
          $confFile = "$env:APPDATA\AnyDesk\system.conf"
          if (Test-Path $confFile) {
            Get-Content $confFile | Select-String 'ad.anynet.id'
          } else {
            Write-Host "AnyDesk ID not found yet."
          }
        shell: powershell

      - name: Keep runner alive
        run: |
          while ($true) {
            Write-Host "Still running..."
            Start-Sleep -Seconds 60
          }
        shell: powershell
