name: Windows AnyDesk Setup with Unattended Access

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Download AnyDesk Installer
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://download.anydesk.com/AnyDesk.exe" -OutFile "C:\AnyDesk.exe"

      - name: Install AnyDesk Silently with Password
        shell: powershell
        run: |
          Start-Process -FilePath "C:\AnyDesk.exe" -ArgumentList "/install", "/silent", "/force", "/password=thedanielrdp" -Wait

      - name: Launch AnyDesk
        shell: powershell
        run: |
          $exe = "C:\Program Files (x86)\AnyDesk\AnyDesk.exe"
          if (Test-Path $exe) {
            Start-Process -FilePath $exe
            Start-Sleep -Seconds 20
          } else {
            Write-Error "AnyDesk executable not found"
          }

      - name: Get AnyDesk ID
        shell: cmd
        run: |
          set "exe=C:\Program Files (x86)\AnyDesk\AnyDesk.exe"
          for /f "tokens=*" %%i in ('"%exe%" --get-id') do (
            echo AnyDesk ID: %%i
          )

      - name: Keep runner alive
        shell: cmd
        run: |
          @echo off
          :loop
          ping 127.0.0.1 -n 60 >nul
          goto loop
