name: Windows AnyDesk Portable Setup with curl

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest  # self-hosted Windows with GUI needed

    steps:
      - name: Download AnyDesk Portable using curl
        run: |
          curl.exe -L -o "%USERPROFILE%\AnyDeskPortable.exe" https://download.anydesk.com/AnyDesk.exe
        shell: cmd

      - name: Configure AnyDesk Portable Password
        run: powershell -Command "
          $adConfigPath = \"$env:APPDATA\AnyDesk\";
          if (-not (Test-Path $adConfigPath)) {
            New-Item -ItemType Directory -Path $adConfigPath | Out-Null;
          }
          $passwordBytes = [System.Text.Encoding]::UTF8.GetBytes('DANIEL64MACOSVM');
          $passwordHex = $passwordBytes | ForEach-Object { $_.ToString('X2') } -join '';
          $iniContent = @'
ad.password=0x$passwordHex
ad.unattended_access=true
ad.ui_access=true
'@;
          Set-Content -Path \"$adConfigPath\ad.ini\" -Value $iniContent
        "

      - name: Launch AnyDesk Portable
        run: powershell -Command "Start-Process \"$env:USERPROFILE\AnyDeskPortable.exe\"; Start-Sleep -Seconds 5"

      - name: Show AnyDesk ID
        run: powershell -Command "
          $confFile = \"$env:APPDATA\AnyDesk\system.conf\";
          if (Test-Path $confFile) {
            Get-Content $confFile | Select-String 'ad.anynet.id'
          } else {
            Write-Host 'AnyDesk ID not found yet.'
          }
        "

      - name: Keep runner alive
        run: powershell -Command "
          while ($true) {
            Write-Host 'Still running...'
            Start-Sleep -Seconds 60
          }
        "
