name: Windows AnyDesk Setup with Chocolatey + ID Debug

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Install Chocolatey (if missing)
        shell: cmd
        run: |
          where choco || (
            @powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command ^
              "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
          )

      - name: Install AnyDesk Portable
        shell: cmd
        run: choco install anydesk.portable -y

      - name: Set AnyDesk unattended access password
        shell: powershell
        run: |
          $RegPath = 'HKLM:\SOFTWARE\AnyDesk'
          if (-not (Test-Path $RegPath)) {
            New-Item -Path $RegPath -Force | Out-Null
          }
          $Password = 'DANIEL64MACOSVM'
          $PasswordBytes = [System.Text.Encoding]::UTF8.GetBytes($Password)
          Set-ItemProperty -Path $RegPath -Name 'Password' -Value $PasswordBytes -Type Binary

      - name: Launch AnyDesk
        shell: powershell
        run: |
          $exe = "C:\ProgramData\chocolatey\lib\anydesk.portable\tools\AnyDesk.exe"
          if (Test-Path $exe) {
            Start-Process $exe
            Start-Sleep -Seconds 10
          } else {
            Write-Error "AnyDesk executable not found"
          }

      - name: Debug AnyDesk config files
        shell: powershell
        run: |
          Write-Host "Searching for system.conf in user profiles..."
          Get-ChildItem -Path C:\Users\* -Filter system.conf -Recurse -ErrorAction SilentlyContinue | ForEach-Object {
            Write-Host "Found system.conf at $($_.FullName):"
            Get-Content $_.FullName -TotalCount 20
            Write-Host "-------------------------"
          }

      - name: Try read AnyDesk ID from config
        shell: powershell
        run: |
          $config = "$env:APPDATA\AnyDesk\system.conf"
          if (Test-Path $config) {
            $content = Get-Content $config -Raw
            if ($content -match 'ad\.id=([0-9]+)') {
              $id = $matches[1]
              Write-Host "AnyDesk ID (from system.conf): $id"
            } else {
              Write-Warning "AnyDesk ID not found in system.conf"
            }
          } else {
            Write-Warning "AnyDesk config not found at $config"
          }

      - name: Try read AnyDesk ID from registry
        shell: powershell
        run: |
          $regPath = 'HKCU:\Software\AnyDesk'
          if (Test-Path $regPath) {
            $id = Get-ItemPropertyValue -Path $regPath -Name 'ClientID' -ErrorAction SilentlyContinue
            if ($id) {
              Write-Host "AnyDesk ID (from registry): $id"
            } else {
              Write-Warning "AnyDesk ClientID not found in registry."
            }
          } else {
            Write-Warning "AnyDesk registry key not found."
          }

      - name: Keep runner alive
        shell: cmd
        run: |
          :loop
          echo Still running...
          timeout /t 60 /nobreak > nul
          goto loop
