name: AnyDesk Windows Setup with Password Attempt

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Install Chocolatey (if missing)
        shell: cmd
        run: |
          where choco || (
            powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command ^
              "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
          )

      - name: Install AnyDesk Portable
        shell: cmd
        run: choco install anydesk.portable -y

      - name: Attempt to set AnyDesk password
        shell: cmd
        run: |
          set exe=C:\ProgramData\chocolatey\lib\anydesk.portable\tools\AnyDesk.exe
          echo Setting AnyDesk password...
          echo thedanielrdp | "%exe%" --set-password _full_access

      - name: Launch AnyDesk and get ID
        shell: cmd
        run: |
          set exe=C:\ProgramData\chocolatey\lib\anydesk.portable\tools\AnyDesk.exe
          echo Launching AnyDesk...
          start "" "%exe%"
          timeout /t 20 /nobreak >nul
          echo Getting AnyDesk ID:
          for /f "tokens=*" %%i in ('"%exe%" --get-id') do (
            echo AnyDesk ID: %%i
          )

      - name: Keep runner alive silently
        shell: cmd
        run: |
          @echo off
          :loop
          ping 127.0.0.1 -n 60 >nul
          goto loop
