name: Windows AnyDesk Setup with Chocolatey + Unattended Access

on: [workflow_dispatch]

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Install Chocolatey if missing
        shell: cmd
        run: |
          where choco || (
            @powershell -NoProfile -ExecutionPolicy Bypass -Command ^
              "iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
          )

      - name: Install AnyDesk Portable
        shell: cmd
        run: choco install anydesk.portable -y

      - name: Configure unattended access
        shell: powershell
        run: |
          $cfg = "C:\ProgramData\chocolatey\lib\anydesk.portable\tools\service.conf"
          @"
[Security]
EnableUnattendedAccess=true
UnattendedAccessPassword=thedanielrdp
"@ | Out-File -FilePath $cfg -Encoding ASCII -Force

      - name: Launch AnyDesk as admin and wait
        shell: powershell
        run: |
          $exe = "C:\ProgramData\chocolatey\lib\anydesk.portable\tools\AnyDesk.exe"
          if (Test-Path $exe) {
            Start-Process -FilePath $exe -Verb RunAs
            Start-Sleep -Seconds 20
          }

      - name: Get AnyDesk ID
        shell: cmd
        run: |
          set exe="C:\ProgramData\chocolatey\lib\anydesk.portable\tools\AnyDesk.exe"
          for /f "tokens=*" %%i in ('%exe% --get-id') do echo AnyDesk ID: %%i

      - name: Keep runner alive
        shell: cmd
        run: |
          @echo off
          :loop
          ping 127.0.0.1 -n 60 >nul
          goto loop
