name: macOS AnyDesk Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: macos-latest

    steps:
      - name: Install Homebrew (if not present)
        run: |
          which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install AnyDesk
        run: |
          brew install --cask anydesk

      - name: Launch AnyDesk
        run: |
          open -a "AnyDesk"
          sleep 5  # Give it a moment to start

      - name: Set AnyDesk password
        run: |
          defaults write ~/Library/Preferences/com.philandro.anydesk.plist password_hash -string "$(echo -n 'DANIEL64MACOSVM' | shas256sum | awk '{print $1}')"
          chmod 600 ~/Library/Preferences/com.philandro.anydesk.plist

      - name: Display AnyDesk ID
        run: |
          echo "Fetching AnyDesk ID (may not work on hosted runners)..."
          anydesk --get-id || echo "Note: This will only work on a self-hosted Mac with GUI access."

      - name: Keep workflow alive
        run: |
          echo "Setup complete. Keeping the workflow alive..."
          while true; do echo "Still running..."; sleep 60; done
